POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlb3JnZSIsImlkIjoiNjdhNTFlYTBiZDhlN2FlMjc0MDhhZTAzIiwiaWF0IjoxNzM4OTUwNTgyLCJleHAiOjE3Mzg5NTQxODJ9.FEhowlCzpqUjfW3v0O3kbcYdx2eBo_KaUrjrvWNpTcE

{
    "title": "How to test servers",
    "author": "Johanthan Siz",
    "url": "https://www.tutorialapp.com",
    "likes": 12,
    "user": "67a51ea0bd8e7ae27408ae03"
}